"""adds producers column for albums

Revision ID: 3b447397fe9e
Revises: 6646bbcec33d
Create Date: 2017-11-13 16:42:21.401269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b447397fe9e'
down_revision = '6646bbcec33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('producers', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'producers')
    # ### end Alembic commands ###
